# NeuroShield AI: Exploratory Data Analysis of Stroke Risk Factors

## 1. INTRODUCTION

This notebook analyzes the trends, patterns, relationships, and unusual observations in *BRFSS* cleaned datset for specifically stroke prediction.

While this notebook is specifically focuesd on EDA this project has focus on predictive machine learning.

## 2. PROBLEM STATEMENT
Stroke occurrence is influenced by various demographic, health, and lifestyle factors. Understanding the patterns and relationships among these factors is essential for identifying characteristics associated with stroke risk.

This exploratory data analysis focuses on examining the distribution of patient characteristics, data quality, class imbalance, and relationships between health-related attributes and stroke occurrence in the NeuroShield AI dataset.

The objective is to uncover meaningful patterns, identify potential anomalies, and generate insights that can support further analysis and predictive modeling.

## 3. OBJECTIVES

The main objectives of this exploratory data analysis are:

- Understand the Dataset: Examine the structure, features, dimensions, and data types of the stroke dataset.
- Assess Data Quality: Inconsistent data, and potential anomalies.
- Analyze Patient Characteristics: Explore the distribution of demographic, health, and lifestyle-related attributes.
- Investigate Class Imbalance: Examine the distribution of stroke and non-stroke cases in the dataset.
- Identify Relationships: Analyze relationships between patient characteristics and stroke occurrence using appropriate visualizations.
- Detect Outliers: Identify and investigate unusual values in relevant numerical variables.
- Explore Feature Associations: Examine relationships among numerical features using statistical summaries and correlation analysis.
- Generate Key Insights: Summarize meaningful patterns and observations that can support future stroke-risk prediction modeling.

## 4. KEY QUESTIONS

1. What are the demographic and health characteristics of patients in the dataset?
2. How is the dataset distributed across the stroke and non-stroke classes?
3. Are there missing values, duplicate records, inconsistencies, or anomalies in the dataset?
4. How are numerical variables such as age, average glucose level, and BMI distributed?
5. How do demographic factors such as gender, age, and marital status vary across stroke and non-stroke patients?
6. Is there a relationship between age and stroke occurrence?
7. How are health conditions such as hypertension and heart disease associated with stroke occurrence?
8. Do lifestyle-related factors, such as smoking status and work type, show differences between stroke and non-stroke patients?
9. How does the distribution of average glucose level and BMI differ between stroke and non-stroke groups?
10. Are there significant relationships or correlations among numerical variables that may be relevant to stroke-risk analysis?
11. Are there any outliers or unusual observations that could affect the analysis?
12. What meaningful patterns and insights can be identified to support further predictive modeling?

## 5. Import Libraries

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

## Load dataset

In [2]:
df= pd.read_csv("../dataset/processed/transformed_train.csv")
print(f"Dataset loaded successfully: {df.shape[0]:,} rows × {df.shape[1]} columns")
df.head()

Dataset loaded successfully: 345,242 rows × 48 columns

,binary__Sex_of_Respondent_Male,"binary__Adults_who_have_been_told_they_have_high_blood_pressure_by_a_doctor,_nurse,_or_other_health_professional_Yes",binary__Have_you_smoked_at_least_100_cigarettes_in_your_entire_life?_[Note:_5_packs_=_100_cigarettes]_Yes,binary__Respondents_that_have_ever_reported_having_coronary_heart_disease_(CHD)_or_myocardial_infarction_(MI)_Reported having MI or CHD,"binary__(Ever_told)_you_had_a_heart_attack,_also_called_a_myocardial_infarction?_Yes",binary__(Ever_told)_(you_had)_angina_or_coronary_heart_disease?_Yes,"binary__Have_you_ever_been_told_by_a_doctor,_nurse_or_other_health_professional_that_your_cholesterol_is_high?_Yes",binary__Are_you_currently_taking_medicine_prescribed_by_your_doctor_or_other_health_professional_for_your_cholesterol?_Yes,"binary__During_the_past_month,_other_than_your_regular_job,_did_you_participate_in_any_physical_activities_or_exercises_such_as_running,_calisthenics,_golf,_gardening,_or_walking_for_exercise?_Yes",binary__Adults_who_reported_doing_physical_activity_or_exercise_during_the_past_30_days_other_than_their_regular_job_No physical activity or exercise in last 30 days,...,multi__Are_you:_(marital_status)_Widowed,ordinal__Would_you_say_that_in_general_your_health_is:,ordinal__What_is_the_highest_grade_or_year_of_school_you_completed?,"ordinal__Is_your_annual_household_income_from_all_sources:_(If_respondent_refuses_at_any_income_level,_code_Refused.)",remainder__Imputed_Age_value_collapsed_above_80,remainder__Body_Mass_Index_(BMI),remainder__Minutes_of_Physical_Activity_per_week_for_First_Activity,"remainder__Now_thinking_about_your_physical_health,_which_includes_physical_illness_and_injury,_for_how_many_days_during_the_past_30_days_was_your_physical_health_not_good?","remainder__Now_thinking_about_your_mental_health,_which_includes_stress,_depression,_and_problems_with_emotions,_for_how_many_days_during_the_past_30_days_was_your_mental_health_not_good?",(Ever_told)_(you_had)_a_stroke.
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,5.0,5.0,60.0,27.40,40.0,20.0,20.0,0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,3.0,4.0,6.0,78.0,27.26,240.0,6.0,7.0,0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,2.0,5.0,6.0,51.0,31.47,360.0,6.0,7.0,0
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,2.0,5.0,9.0,23.0,24.41,50.0,6.0,1.0,0
4,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,1.0,2.0,3.0,2.0,68.0,34.41,160.0,6.0,7.0,0

## Basic understanding

In [3]:
print("Shape:", df.shape)
print("Column : ", df.columns.to_list())

Shape: (345242, 48)
Column :  ['binary__Sex_of_Respondent_Male', 'binary__Adults_who_have_been_told_they_have_high_blood_pressure_by_a_doctor,_nurse,_or_other_health_professional_Yes', 'binary__Have_you_smoked_at_least_100_cigarettes_in_your_entire_life?_[Note:_5_packs_=_100_cigarettes]_Yes', 'binary__Respondents_that_have_ever_reported_having_coronary_heart_disease_(CHD)_or_myocardial_infarction_(MI)_Reported having MI or CHD', 'binary__(Ever_told)_you_had_a_heart_attack,_also_called_a_myocardial_infarction?_Yes', 'binary__(Ever_told)_(you_had)_angina_or_coronary_heart_disease?_Yes', 'binary__Have_you_ever_been_told_by_a_doctor,_nurse_or_other_health_professional_that_your_cholesterol_is_high?_Yes', 'binary__Are_you_currently_taking_medicine_prescribed_by_your_doctor_or_other_health_professional_for_your_cholesterol?_Yes', 'binary__During_the_past_month,_other_than_your_regular_job,_did_you_participate_in_any_physical_activities_or_exercises_such_as_running,_calisthenics,_golf,_gardening,_or_walking_for_exercise?_Yes', 'binary__Adults_who_reported_doing_physical_activity_or_exercise_during_the_past_30_days_other_than_their_regular_job_No physical activity or exercise in last 30 days', 'binary__Physical_Activity_Index_Meet Aerobic Recommendations', 'binary__Adults_that_participated_in_greater_than_300_minutes_(or_vigorous_equivalent_minutes)_of_physical_activity_per_week_(2-levels)._301+ minutes (or vigorous equivalent minutes) of physical activity', 'multi__(Ever_told)_(you_had)_diabetes?_(If_Yes_-_and_respondent_is_female,_ask_Was_this_only_when_you_were_pregnant?_If_Respondent_says_pre-diabetes_or_borderline_diabetes,_use_response_code_4.)_No', 'multi__(Ever_told)_(you_had)_diabetes?_(If_Yes_-_and_respondent_is_female,_ask_Was_this_only_when_you_were_pregnant?_If_Respondent_says_pre-diabetes_or_borderline_diabetes,_use_response_code_4.)_No, pre-diabetes or borderline diabetes', 'multi__(Ever_told)_(you_had)_diabetes?_(If_Yes_-_and_respondent_is_female,_ask_Was_this_only_when_you_were_pregnant?_If_Respondent_says_pre-diabetes_or_borderline_diabetes,_use_response_code_4.)_Yes', 'multi__(Ever_told)_(you_had)_diabetes?_(If_Yes_-_and_respondent_is_female,_ask_Was_this_only_when_you_were_pregnant?_If_Respondent_says_pre-diabetes_or_borderline_diabetes,_use_response_code_4.)_Yes, but female told only during pregnancy', 'multi__Four-level_smoker_status:_Everyday_smoker,_Someday_smoker,_Former_smoker,_Non-smoker_Current smoker', 'multi__Four-level_smoker_status:_Everyday_smoker,_Someday_smoker,_Former_smoker,_Non-smoker_Former smoker', 'multi__Four-level_smoker_status:_Everyday_smoker,_Someday_smoker,_Former_smoker,_Non-smoker_Never smoked', "multi__Not_including_kidney_stones,_bladder_infection_or_incontinence,_were_you_ever_told_you_had_kidney_disease?_Don't know / Not sure", 'multi__Not_including_kidney_stones,_bladder_infection_or_incontinence,_were_you_ever_told_you_had_kidney_disease?_No', 'multi__Not_including_kidney_stones,_bladder_infection_or_incontinence,_were_you_ever_told_you_had_kidney_disease?_Yes', "multi__Has_a_doctor_or_other_health_professional_ever_told_you_that_you_had_prediabetes_or_borderline_diabetes?_(If_Yes_-_and_respondent_is_female,_ask:_'Was_this_only_when_you_were_pregnant?')_No", "multi__Has_a_doctor_or_other_health_professional_ever_told_you_that_you_had_prediabetes_or_borderline_diabetes?_(If_Yes_-_and_respondent_is_female,_ask:_'Was_this_only_when_you_were_pregnant?')_Yes", "multi__Has_a_doctor_or_other_health_professional_ever_told_you_that_you_had_prediabetes_or_borderline_diabetes?_(If_Yes_-_and_respondent_is_female,_ask:_'Was_this_only_when_you_were_pregnant?')_Yes, during pregnancy", 'multi__Are_you_currently?_A homemaker', 'multi__Are_you_currently?_A student', 'multi__Are_you_currently?_Employed for wages', 'multi__Are_you_currently?_Out of work for 1 year or more', 'multi__Are_you_currently?_Out of work for less than 1 year', 'multi__Are_you_currently?_Retired', 'multi__Are_you_currently?_Self-employed', 'multi__Are_you_currently?_Unable to work', 'multi__Are_you:_(marital_status)_A member of an unmarried couple', 'multi__Are_you:_(marital_status)_Divorced', 'multi__Are_you:_(marital_status)_Married', 'multi__Are_you:_(marital_status)_Never married', 'multi__Are_you:_(marital_status)_Separated', 'multi__Are_you:_(marital_status)_Widowed', 'ordinal__Would_you_say_that_in_general_your_health_is:', 'ordinal__What_is_the_highest_grade_or_year_of_school_you_completed?', 'ordinal__Is_your_annual_household_income_from_all_sources:_(If_respondent_refuses_at_any_income_level,_code_Refused.)', 'remainder__Imputed_Age_value_collapsed_above_80', 'remainder__Body_Mass_Index_(BMI)', 'remainder__Minutes_of_Physical_Activity_per_week_for_First_Activity', 'remainder__Now_thinking_about_your_physical_health,_which_includes_physical_illness_and_injury,_for_how_many_days_during_the_past_30_days_was_your_physical_health_not_good?', 'remainder__Now_thinking_about_your_mental_health,_which_includes_stress,_depression,_and_problems_with_emotions,_for_how_many_days_during_the_past_30_days_was_your_mental_health_not_good?', '(Ever_told)_(you_had)_a_stroke.']

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345242 entries, 0 to 345241
Data columns (total 48 columns):
 #   Column                                                                                                                                                                                                                                         Non-Null Count   Dtype
---  ------                                                                                                                                                                                                                                         --------------   -----
 0   binary__Sex_of_Respondent_Male                                                                                                                                                                                                                 345242 non-null  float64
 1   binary__Adults_who_have_been_told_they_have_high_blood_pressure_by_a_doctor,_nurse,_or_other_health_professional_Yes                                                                                                                           345242 non-null  float64
 2   binary__Have_you_smoked_at_least_100_cigarettes_in_your_entire_life?_[Note:_5_packs_=_100_cigarettes]_Yes                                                                                                                                      345242 non-null  float64
 3   binary__Respondents_that_have_ever_reported_having_coronary_heart_disease_(CHD)_or_myocardial_infarction_(MI)_Reported having MI or CHD                                                                                                        345242 non-null  float64
 4   binary__(Ever_told)_you_had_a_heart_attack,_also_called_a_myocardial_infarction?_Yes                                                                                                                                                           345242 non-null  float64
 5   binary__(Ever_told)_(you_had)_angina_or_coronary_heart_disease?_Yes                                                                                                                                                                            345242 non-null  float64
 6   binary__Have_you_ever_been_told_by_a_doctor,_nurse_or_other_health_professional_that_your_cholesterol_is_high?_Yes                                                                                                                             345242 non-null  float64
 7   binary__Are_you_currently_taking_medicine_prescribed_by_your_doctor_or_other_health_professional_for_your_cholesterol?_Yes                                                                                                                     345242 non-null  float64
 8   binary__During_the_past_month,_other_than_your_regular_job,_did_you_participate_in_any_physical_activities_or_exercises_such_as_running,_calisthenics,_golf,_gardening,_or_walking_for_exercise?_Yes                                           345242 non-null  float64
 9   binary__Adults_who_reported_doing_physical_activity_or_exercise_during_the_past_30_days_other_than_their_regular_job_No physical activity or exercise in last 30 days                                                                          345242 non-null  float64
 10  binary__Physical_Activity_Index_Meet Aerobic Recommendations                                                                                                                                                                                   345242 non-null  float64
 11  binary__Adults_that_participated_in_greater_than_300_minutes_(or_vigorous_equivalent_minutes)_of_physical_activity_per_week_(2-levels)._301+ minutes (or vigorous equivalent minutes) of physical activity                                     345242 non-null  float64
 12  multi__(Ever_told)_(you_had)_diabetes?_(If_Yes_-_and_respondent_is_female,_ask_Was_this_only_when_you_were_pregnant?_If_Respondent_says_pre-diabetes_or_borderline_diabetes,_use_response_code_4.)_No                                          345242 non-null  float64
 13  multi__(Ever_told)_(you_had)_diabetes?_(If_Yes_-_and_respondent_is_female,_ask_Was_this_only_when_you_were_pregnant?_If_Respondent_says_pre-diabetes_or_borderline_diabetes,_use_response_code_4.)_No, pre-diabetes or borderline diabetes     345242 non-null  float64
 14  multi__(Ever_told)_(you_had)_diabetes?_(If_Yes_-_and_respondent_is_female,_ask_Was_this_only_when_you_were_pregnant?_If_Respondent_says_pre-diabetes_or_borderline_diabetes,_use_response_code_4.)_Yes                                         345242 non-null  float64
 15  multi__(Ever_told)_(you_had)_diabetes?_(If_Yes_-_and_respondent_is_female,_ask_Was_this_only_when_you_were_pregnant?_If_Respondent_says_pre-diabetes_or_borderline_diabetes,_use_response_code_4.)_Yes, but female told only during pregnancy  345242 non-null  float64
 16  multi__Four-level_smoker_status:_Everyday_smoker,_Someday_smoker,_Former_smoker,_Non-smoker_Current smoker                                                                                                                                     345242 non-null  float64
 17  multi__Four-level_smoker_status:_Everyday_smoker,_Someday_smoker,_Former_smoker,_Non-smoker_Former smoker                                                                                                                                      345242 non-null  float64
 18  multi__Four-level_smoker_status:_Everyday_smoker,_Someday_smoker,_Former_smoker,_Non-smoker_Never smoked                                                                                                                                       345242 non-null  float64
 19  multi__Not_including_kidney_stones,_bladder_infection_or_incontinence,_were_you_ever_told_you_had_kidney_disease?_Don't know / Not sure                                                                                                        345242 non-null  float64
 20  multi__Not_including_kidney_stones,_bladder_infection_or_incontinence,_were_you_ever_told_you_had_kidney_disease?_No                                                                                                                           345242 non-null  float64
 21  multi__Not_including_kidney_stones,_bladder_infection_or_incontinence,_were_you_ever_told_you_had_kidney_disease?_Yes                                                                                                                          345242 non-null  float64
 22  multi__Has_a_doctor_or_other_health_professional_ever_told_you_that_you_had_prediabetes_or_borderline_diabetes?_(If_Yes_-_and_respondent_is_female,_ask:_'Was_this_only_when_you_were_pregnant?')_No                                           345242 non-null  float64
 23  multi__Has_a_doctor_or_other_health_professional_ever_told_you_that_you_had_prediabetes_or_borderline_diabetes?_(If_Yes_-_and_respondent_is_female,_ask:_'Was_this_only_when_you_were_pregnant?')_Yes                                          345242 non-null  float64
 24  multi__Has_a_doctor_or_other_health_professional_ever_told_you_that_you_had_prediabetes_or_borderline_diabetes?_(If_Yes_-_and_respondent_is_female,_ask:_'Was_this_only_when_you_were_pregnant?')_Yes, during pregnancy                        345242 non-null  float64
 25  multi__Are_you_currently?_A homemaker                                                                                                                                                                                                          345242 non-null  float64
 26  multi__Are_you_currently?_A student                                                                                                                                                                                                            345242 non-null  float64
 27  multi__Are_you_currently?_Employed for wages                                                                                                                                                                                                   345242 non-null  float64
 28  multi__Are_you_currently?_Out of work for 1 year or more                                                                                                                                                                                       345242 non-null  float64
 29  multi__Are_you_currently?_Out of work for less than 1 year                                                                                                                                                                                     345242 non-null  float64
 30  multi__Are_you_currently?_Retired                                                                                                                                                                                                              345242 non-null  float64
 31  multi__Are_you_currently?_Self-employed                                                                                                                                                                                                        345242 non-null  float64
 32  multi__Are_you_currently?_Unable to work                                                                                                                                                                                                       345242 non-null  float64
 33  multi__Are_you:_(marital_status)_A member of an unmarried couple                                                                                                                                                                               345242 non-null  float64
 34  multi__Are_you:_(marital_status)_Divorced                                                                                                                                                                                                      345242 non-null  float64
 35  multi__Are_you:_(marital_status)_Married                                                                                                                                                                                                       345242 non-null  float64
 36  multi__Are_you:_(marital_status)_Never married                                                                                                                                                                                                 345242 non-null  float64
 37  multi__Are_you:_(marital_status)_Separated                                                                                                                                                                                                     345242 non-null  float64
 38  multi__Are_you:_(marital_status)_Widowed                                                                                                                                                                                                       345242 non-null  float64
 39  ordinal__Would_you_say_that_in_general_your_health_is:                                                                                                                                                                                         345242 non-null  float64
 40  ordinal__What_is_the_highest_grade_or_year_of_school_you_completed?                                                                                                                                                                            345242 non-null  float64
 41  ordinal__Is_your_annual_household_income_from_all_sources:_(If_respondent_refuses_at_any_income_level,_code_Refused.)                                                                                                                          345242 non-null  float64
 42  remainder__Imputed_Age_value_collapsed_above_80                                                                                                                                                                                                345242 non-null  float64
 43  remainder__Body_Mass_Index_(BMI)                                                                                                                                                                                                               345242 non-null  float64
 44  remainder__Minutes_of_Physical_Activity_per_week_for_First_Activity                                                                                                                                                                            345242 non-null  float64
 45  remainder__Now_thinking_about_your_physical_health,_which_includes_physical_illness_and_injury,_for_how_many_days_during_the_past_30_days_was_your_physical_health_not_good?                                                                   345242 non-null  float64
 46  remainder__Now_thinking_about_your_mental_health,_which_includes_stress,_depression,_and_problems_with_emotions,_for_how_many_days_during_the_past_30_days_was_your_mental_health_not_good?                                                    345242 non-null  float64
 47  (Ever_told)_(you_had)_a_stroke.                                                                                                                                                                                                                345242 non-null  int64
dtypes: float64(47), int64(1)
memory usage: 126.4 MB

In [5]:
df.sample(5)

,binary__Sex_of_Respondent_Male,"binary__Adults_who_have_been_told_they_have_high_blood_pressure_by_a_doctor,_nurse,_or_other_health_professional_Yes",binary__Have_you_smoked_at_least_100_cigarettes_in_your_entire_life?_[Note:_5_packs_=_100_cigarettes]_Yes,binary__Respondents_that_have_ever_reported_having_coronary_heart_disease_(CHD)_or_myocardial_infarction_(MI)_Reported having MI or CHD,"binary__(Ever_told)_you_had_a_heart_attack,_also_called_a_myocardial_infarction?_Yes",binary__(Ever_told)_(you_had)_angina_or_coronary_heart_disease?_Yes,"binary__Have_you_ever_been_told_by_a_doctor,_nurse_or_other_health_professional_that_your_cholesterol_is_high?_Yes",binary__Are_you_currently_taking_medicine_prescribed_by_your_doctor_or_other_health_professional_for_your_cholesterol?_Yes,"binary__During_the_past_month,_other_than_your_regular_job,_did_you_participate_in_any_physical_activities_or_exercises_such_as_running,_calisthenics,_golf,_gardening,_or_walking_for_exercise?_Yes",binary__Adults_who_reported_doing_physical_activity_or_exercise_during_the_past_30_days_other_than_their_regular_job_No physical activity or exercise in last 30 days,...,multi__Are_you:_(marital_status)_Widowed,ordinal__Would_you_say_that_in_general_your_health_is:,ordinal__What_is_the_highest_grade_or_year_of_school_you_completed?,"ordinal__Is_your_annual_household_income_from_all_sources:_(If_respondent_refuses_at_any_income_level,_code_Refused.)",remainder__Imputed_Age_value_collapsed_above_80,remainder__Body_Mass_Index_(BMI),remainder__Minutes_of_Physical_Activity_per_week_for_First_Activity,"remainder__Now_thinking_about_your_physical_health,_which_includes_physical_illness_and_injury,_for_how_many_days_during_the_past_30_days_was_your_physical_health_not_good?","remainder__Now_thinking_about_your_mental_health,_which_includes_stress,_depression,_and_problems_with_emotions,_for_how_many_days_during_the_past_30_days_was_your_mental_health_not_good?",(Ever_told)_(you_had)_a_stroke.
234344,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,2.0,4.0,7.0,51.0,25.13,135.0,3.0,7.0,1
125712,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,3.0,5.0,6.0,80.0,25.33,180.0,5.0,7.0,0
270376,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,4.0,3.0,4.0,22.0,34.87,210.0,6.0,7.0,0
23313,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,2.0,4.0,1.0,38.0,25.06,210.0,6.0,25.0,0
237997,1.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,0.0,0.0,4.0,6.0,77.0,35.26,160.0,29.0,2.0,0

### variable groups 
1. **Basic User Information**-